
# Name of your site (displayed in the header)
name: Syed Hassan Ali
title: Syed Hassan Ali
language: html "en"
email: upodesta@gmail.com

# Short bio or description (displayed in the header)
description: Syed Hassan Ali is an awesome front end web designer and web developer. With his 11 years of experience, he take care almost every possible solutions for your unique online identity within a limited budget
keywords: Syed Hassan Ali, web designer, web developer, web hosting, domain name registration, e-mail marketing, social marketing, Search Engine Optimization (SEO), Data management, UI/UA Designer, Consultancy, Free Web Hosting, Free Sub domain, Dhaka, Bangladesh


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL 
# Used for Sitemap.xml and your RSS feed
url: https://www.syedhassanali.com
     
baseurl: https://www.syedhassanali.com

